# .goreleaser.yml
version: '2'

project_name: naabu
builds:
  - id: naabu
    dir: v2/cmd/naabu
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md