name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Install upx
        run: sudo apt install upx -y
        continue-on-error: true

      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Run GoReleaser
        run: goreleaser release
        working-directory: v2/cmd/naabu/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPATH: "/home/runner/go"

